// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgowHtnxP4QhC8KNMkTkMRj7ZAB6JLtOA',
    appId: '1:799050441526:web:0158fb60fa98c068314997',
    messagingSenderId: '799050441526',
    projectId: 'homeus-f7ce6',
    authDomain: 'homeus-f7ce6.firebaseapp.com',
    storageBucket: 'homeus-f7ce6.appspot.com',
    measurementId: 'G-Y1V1NB3QGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ0km2PKkfDYAhq3koaEBH9FZaKr4V8mE',
    appId: '1:799050441526:android:534a685880a72dab314997',
    messagingSenderId: '799050441526',
    projectId: 'homeus-f7ce6',
    storageBucket: 'homeus-f7ce6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSp9j1U-7y9HsWH1CfcYrRIRKLBbJkemE',
    appId: '1:799050441526:ios:d48a4ec8ea993673314997',
    messagingSenderId: '799050441526',
    projectId: 'homeus-f7ce6',
    storageBucket: 'homeus-f7ce6.appspot.com',
    androidClientId: '799050441526-ha1f81e0ih1ht9oj2o36fkqkf2kqahhv.apps.googleusercontent.com',
    iosClientId: '799050441526-f5c6scdt8atc91u41hc6ngr128tngupu.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeScanner',
  );
}
